// RootLayout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Carvach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen relative bg-gradient-to-br from-black to-[#4b573f] via-black pt-28 sm:pt-36 font-kode-mono">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
